# vim:ft=ansible:
name: dev

windows:
  - main:
      layout: a5c5,364x99,0,0[364x69,0,0,0,364x29,0,70{120x29,0,70,2,120x29,121,70,3,122x29,242,70,4}]

      #we change the directory here because tmuxinator expands the alias and
      #makes a really long path
      panes:
        - vim:
          - cd ~/OSCP/ && clear
          - vim
        - lower1:
          - cd ~/OSCP/ && clear
        - lower2:
          - cd ~/OSCP/ && clear
        - lower3:
          - cd ~/OSCP/ && clear

  - cli:
      layout: tiled
      panes:
        - one:
          - cd ~/OSCP/ && clear
        - two:
        - three:
        - vpn:
          - cd ~/OSCP/ && clear
          - cd ./lab-connection
          - openvpn ./OS-38584-PWK.ovpn

